# syntax=docker/dockerfile:1
# For Ubuntu 20.04:
FROM ubuntu:focal

ARG NMS_URL

# NGINX Instance Manager agent setup
RUN mkdir /deployment
COPY ./nginx-plus/container/start_nap.sh /deployment/
RUN chmod +x /deployment/start_nap.sh && touch /.dockerenv

# Download certificate and key from the customer portal (https://account.f5.com)
# and copy to the build context
COPY ./nginx-plus/nginx-repo.crt /etc/ssl/nginx/
COPY ./nginx-plus/nginx-repo.key /etc/ssl/nginx/

# Install prerequisite packages:
RUN apt-get update && apt-get install -y apt-transport-https lsb-release ca-certificates wget gnupg2 curl vim

# Agent installation
RUN bash -c 'curl -k $NMS_URL/install/nginx-agent | sh' && echo "Agent installed from NMS"


# Download and add the NGINX signing keys:
RUN wget https://cs.nginx.com/static/keys/nginx_signing.key && apt-key add nginx_signing.key \
    && wget https://cs.nginx.com/static/keys/app-protect-security-updates.key && apt-key add app-protect-security-updates.key

# Add NGINX Plus repository:
RUN printf "deb https://pkgs.nginx.com/plus/ubuntu `lsb_release -cs` nginx-plus\n" | tee /etc/apt/sources.list.d/nginx-plus.list

# Add NGINX App Protect WAF repositories:
RUN printf "deb https://pkgs.nginx.com/app-protect/ubuntu `lsb_release -cs` nginx-plus\n" | tee /etc/apt/sources.list.d/nginx-app-protect.list \
    && printf "deb https://pkgs.nginx.com/app-protect-security-updates/ubuntu `lsb_release -cs` nginx-plus\n" | tee /etc/apt/sources.list.d/app-protect-security-updates.list

# Download the apt configuration to `/etc/apt/apt.conf.d`:
RUN wget -P /etc/apt/apt.conf.d https://cs.nginx.com/static/files/90pkgs-nginx

# Update the repository and install the most recent version of the NGINX App Protect WAF package (which includes NGINX Plus):
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y app-protect

RUN apt-get install -y "nginx-plus-module-njs"

# Forward request logs to Docker log collector:
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

# Copy configuration files:
COPY ./nginx-plus/container/nginx_nap.conf /etc/nginx/nginx.conf

# Copy NAP log profile for SM monitoring :
COPY ./nginx-plus/container/log_sm.json /etc/app_protect/conf/log_sm.json

EXPOSE 80

STOPSIGNAL SIGTERM

#CMD ["nginx", "-g", "daemon off;"]
CMD /deployment/start_nap.sh
