FROM centos:7

ARG NMS_URL

# Initial packages setup
RUN yum -y update \
	&& yum install -y wget ca-certificates epel-release curl \
# NGINX Instance Manager agent setup
	&& mkdir -p /deployment /etc/ssl/nginx \
# Agent installation
	&& bash -c 'curl -k $NMS_URL/install/nginx-agent | sh' && echo "Agent installed from NMS"

COPY ./nginx-plus/nginx-repo.crt /etc/ssl/nginx/
COPY ./nginx-plus/nginx-repo.key /etc/ssl/nginx/

# Startup script
COPY ./nginx-plus/container/start.sh /deployment/

# Download certificate and key from the customer portal (https://account.f5.com)
# and copy to the build context
RUN set -x \
# Startup script
	&& chmod +x /deployment/start.sh && touch /.dockerenv \
# Install prerequisite packages:
	&& yum -y update \
	&& yum autoremove -y \
	&& yum -y clean all \
	&& rm -rf /var/cache/yum \
	&& wget -P /etc/yum.repos.d https://cs.nginx.com/static/files/nginx-plus-7.4.repo \
#	&& wget -P /etc/yum.repos.d https://cs.nginx.com/static/files/app-protect-7.repo \
#	&& yum install -y app-protect app-protect-attack-signatures
	&& yum install -y nginx-plus nginx-plus-module-njs nginx-plus-module-prometheus \ 
    && rm -rf /etc/apt/apt.conf.d/90nginx /etc/ssl/nginx
# Forward request logs to Docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80
STOPSIGNAL SIGTERM

CMD /deployment/start.sh